data: "data.yaml"
epochs: 300
patience: 5
batch: 8
save: True
save_period: 5
device: "0"
workers: 4 # Number of CPU workers for data loading
project: "weights"
name: "test-1"
exist_ok: True  # Overwrite the existing run for iterative testing, turn false when confident
pretrained: True
optimizer: "auto"
resume: False
amp: True  # Mixed precision training for faster training, might cause some issues
fraction: 1  # Fraction of dataset if resource-limited, change to 1 when confident
profile: True  # Enable ONNX and TensorRT profiling
freeze: null  # Freeze the first N layers or specify layers by index

# Validation parameters
conf: 0.01
iou: 0.6
degrees: 0.0
shear: 0.0
perspective: 0.0
plots: True
half: True  # Use half precision for weaker GPUs
