lr0 : (1e-5, 1e-1)
lrf : (0.01, 1.0)
momentum : (0.3, 0.95)
weight_decay : (0.0, 0.001)
warmup_epochs : (0, 5)
warmup_momentum : (0.3, 0.95)
warmup_bias_lr : (0.0, 0.1)
box : (0.0, 10.0)
cls : (0.0, 10.0)
hsv_v : (0.0, 1.0)
degrees : (0.0, 45.0)
translate : (0.0, 0.1)
scale : (0.0, 2.0)
shear : (0.0, 16.0)
perspective : (0.0, 0.001)
flipud : (0.0, 1.0)
fliplr : (0.0, 1.0)
mosaic : (0.0, 1.0)
mixup : (0.0, 1.0)
copy_paste : (0.0, 1.0)



