#hyperparameter tuning
data: 'D:/FYP_Code/configs/data.yaml'
epochs: 10  #number of epochs
patience: 2  #patience for early stopping
batch: 2 #batch size
save: True #save model
save_period: 10 #save model every 10 epochs
device: 0 #device to use
workers: 1 #number of workers
project: 'tune_test' #project name
name: 'run_1' #run name
exist_ok: True #overwrite existing model
pretrained: True #use pretrained model
optimizer: 'auto' #optimizer
resume: False #resume training
amp: False #use amp
fraction: 0.1  # Use only 10% of data for testing
profile: True #profile training
freeze: null #freeze layers


# Validation parameters
conf: 0.001 #confidence threshold
iou: 0.6 #iou threshold
plots: True #plot training results
half: True #use half precision
